name: Deploy to dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Build, Deploy to S3 bucket
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [12.16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create .env
        shell: bash
        env:
          PROD_APP_ID: ${{ secrets.PROD_APP_ID }}
          PROD_API_BASE_URL: ${{ secrets.PROD_API_URL }}
          PROD_MINI_PRESET_URL: ${{ secrets.PROD_MINI_PRESET_URL }}
        run: |
          touch .env
          echo REACT_APP_APP_ID="$PROD_APP_ID" >> .env
          echo REACT_APP_API_URL="$PROD_API_URL" >> .env
          echo REACT_APP_MINI_PRESET_URL="$PROD_MINI_PRESET_URL" >> .env
          cat .env

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Transfer to S3 for serving static
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: errand-client-dev
          AWS_ACCESS_KEY_ID: ${{ secrets. AWS_IAM_MANAGER_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
          SOURCE_DIR: "build"
